sudo: false
language: elixir
elixir:
  - 1.3.4
otp_release:
  - 19.0
script:
  - mix test
after_success:
  - MIX_ENV=test mix coveralls.travis
  - mix dialyzer
  - mix credo
notifications:
  email:
    - vertexclique@gmail.com
  on_success: always
  on_failure: always
